name: Sync on Hugging Face hub
on:
  push:
    branches: [main]

  # run this wf manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF_DUKEMLOPSTEST }}
        run: git remote add space https://pmf0770g:$HF@huggingface.co/spaces/pmf0770g/DukeMLOpsTest
      - name: Push to hub
        env:
          HF: ${{ secrets.HF_DUKEMLOPSTEST }}
        run: git push --force https://pmf0770g:$HF@huggingface.co/spaces/pmf0770g/DukeMLOpsTest main
